# Overall Strategy

## User Story
Suppose our user is seeking for some music. Then, he/she opens Spotify, currently one of the most popular media streaming apps in the world. Usually, user can choose between 
two options: listening to self-created playlsts stored in user's own music library, or listening to theme-based playlists generated by Spotify. Suppose our user picks the 
first option and starts listening to his/her own playlists. But one pain point for this scenario is that user usually ends up repeatedly listening to the same group of
songs. This cam quickly makes him/her bored and eagers for something new. <br>
Next
